version: '2'

services:
# you'd have to download spark-bin first, command you can refer:
# wget -v -O apache-spark.tgz "${SPARK_DOWNLOAD_URL}" && mkdir -p ${SPARK_HOME} && tar -xf apache-spark.tgz \
# -C ${SPARK_HOME} --strip-components=1 && rm apache-spark.tgz
  zeppelin:
    build: ./custom-zeppelin
    image: chrisptang/zeppelin:0.10.0
    container_name: zeppelin
    user: "root"
    environment:
      - TZ=Asia/Shanghai
      - ZEPPELIN_ADDR=0.0.0.0
      - SPARK_HOME=/opt/spark
      - ZEPPELIN_LOG_DIR=/logs
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_PORT=8280
      - SPARK_DRIVER_PORT=47077
      - SPARK_DRIVER_BINDADDR=0.0.0.0
      - SPARK_DRIVER_HOST=$HOST_IP
    volumes:
      - ./zeppelin-notebooks:/notebook
      - ./log-received:/log-received
      - ./zeppelin-logs:/logs
      - ./zeppelin-warehouse:/warehouse
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8280:8280
      - 47077:47077
      - 39194:39194

  db-postgres:
    container_name: db-postgres-prod
    image: postgres:10
    ports: 
      - "5432:5432"
    volumes: 
      - ./jupyter-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres-local
      POSTGRES_DB: warehouse
      TZ: Asia/Shanghai
  
  superset:
    container_name: superset-prod
    image: apache/superset:1.4.0rc1
    environment:
      - USER_NAME=admin
      - USER_PASSWORD=$RANDOM_PASSWORD
      - TZ=Asia/Shanghai
    links:
      - "db-postgres:db-postgres"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - custom-superset/init_superset_user.sh:/init_superset_user.sh
    ports:
      - "8088:8088"

  adminer:
    image: adminer:latest
    container_name: adminer-prod
    environment:
      - TZ=Asia/Shanghai
    depends_on: 
      - db-postgres
    ports:
      - 4088:8080

  sourcing-search:
    image: chrisptang/sourcing-search:1.0
    container_name: sourcing-search-prod
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./log-received:/data/logs/received
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on: 
      - db-postgres
    ports:
      - 1688:1688

  scrapy:
    image: chrisptang/scrapy-shopee-nodejs:1.1
    container_name: scrapy-prod
    environment:
      - SINK_URL=http://sourcing-search:1688/api/1688search/sink
      - TASK_SOURCE=database
      - JOB_SCHEDULE=5 0 * * *
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - sourcing-search
      - db-postgres
    ports:
      - 5001:5000