version: '2'

services:
  jupyter:
    container_name: jupyter-prod
    # image: jupyter/pyspark-notebook:latest
    build: ./custom-jupyter
    links:
      - "db-postgres:db-postgres"
    environment:
      - THIS_HOST_IP=$HOST_IP
      - PASSWORD=ptang4312
      - SPARK_OPTS=--master=local[2] --driver-memory=2g --executor-memory=2g
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter-work:/home/jovyan/work
      - ./log-received:/home/jovyan/work/log-received

  db-postgres:
    container_name: db-postgres-prod
    image: postgres:10
    ports: 
      - "5432:5432"
    volumes: 
      - ./jupyter-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres-local
      POSTGRES_DB: warehouse
  
  superset:
    container_name: superset-prod
    # image: apache/superset:1.4.0rc1
    build: ./custom-superset
    links:
      - "db-postgres:db-postgres"
    ports:
      - "8088:8088"

  adminer:
    image: adminer:latest
    container_name: adminer-prod
    depends_on: 
      - db-postgres
    ports:
      - 4088:8080

  sourcing-search:
    image: chrisptang/sourcing-search:1.0
    container_name: sourcing-search-prod
    volumes:
      - ./log-received:/data/logs/received
    depends_on: 
      - db-postgres
    ports:
      - 1688:1688

  scrapy:
    image: chrisptang/scrapy-shopee-nodejs:1.0
    container_name: scrapy-prod
    environment:
      - SINK_URL=http://sourcing-search:1688/api/1688search/sink
      - TASK_SOURCE=database
    depends_on:
      - sourcing-search
    ports:
      - 5001:5000