version: '2'

services:
  spark-master:
    build: ./custom-spark-standalone
    image: chrisptang/cluster-apache-spark:3.1.2
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./spark-apps:/opt/spark-apps
       - ./spark-data:/opt/spark-data
       - ./log-received:/opt/spark-data/log-received
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master

  spark-worker-a:
    image: chrisptang/cluster-apache-spark:3.1.2
    container_name: spark-worker-a
    ports:
      - "9091:8080"
      - "17000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./spark-apps:/opt/spark-apps
       - ./spark-data:/opt/spark-data
       - ./log-received:/opt/spark-data/log-received
  spark-worker-b:
    image: chrisptang/cluster-apache-spark:3.1.2
    container_name: spark-worker-b
    ports:
      - "9092:8080"
      - "17001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./spark-apps:/opt/spark-apps
        - ./spark-data:/opt/spark-data
        - ./log-received:/opt/spark-data/log-received