version: '2'

services:
  spark-master:
    build: ./custom-spark-standalone
    image: chrisptang/cluster-apache-spark:3.1.2
    container_name: spark-master
    hostname: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
      - "39191:39191"
    volumes:
       - ./spark-apps:/opt/spark-apps
       - ./spark-data:/opt/spark-data
       - ./spark-logs:/spark-logs
       - ./log-received:/opt/spark-data/log-received
    environment:
      - SPARK_WORKLOAD=master
      - SPARK_LOCAL_IP=spark-master
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_BLOCK_MANAGER_PORT=39191

  spark-worker-a:
    image: chrisptang/cluster-apache-spark:3.1.2
    container_name: spark-worker-a
    ports:
      - "9091:9091"
      - "17000:17000"
      - "39192:39192"
    hostname: spark-worker-a
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://$HOST_IP:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
      - SPARK_WORKER_PORT=17000
      - SPARK_WORKER_WEBUI_PORT=9091
      - SPARK_BLOCK_MANAGER_PORT=39192
    volumes:
       - ./spark-apps:/opt/spark-apps
       - ./spark-data:/opt/spark-data
       - ./log-received:/opt/spark-data/log-received
       - ./spark-logs:/spark-logs
       
  spark-worker-b:
    image: chrisptang/cluster-apache-spark:3.1.2
    container_name: spark-worker-b
    hostname: spark-worker-a
    ports:
      - "9092:9092"
      - "17001:17001"
      - "39193:39193"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://$HOST_IP:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
      - SPARK_WORKER_PORT=17001
      - SPARK_WORKER_WEBUI_PORT=9092
      - SPARK_BLOCK_MANAGER_PORT=39193
    volumes:
        - ./spark-apps:/opt/spark-apps
        - ./spark-data:/opt/spark-data
        - ./log-received:/opt/spark-data/log-received
        - ./spark-logs:/spark-logs