version: '3'

services:
  zeppelin:
    image: apache/zeppelin:0.10.0
    container_name: zeppelin
    user: $(id -u)
    environment:
      - ZEPPELIN_ADDR=0.0.0.0
      - SPARK_HOME=/opt/spark
      - ZEPPELIN_PORT=8280
      - ZEPPELIN_NOTEBOOK_DIR=/notebook
      - ZEPPELIN_LOG_DIR=/logs
    volumes:
      - ./zeppelin-notebook:/notebook
      - ./log-received:/opt/log-received
      - ./zeppelin-logs:/logs
      - ./spark:/opt/spark
    ports:
      - 8280:8280