let get_sub_categories_url = "https://shopee.co.id/api/v4/pages/get_sub_category_list?parent_catid=11043778";
let shopeeFashionAccessories = {
    "data": {
        "category_list": [
            {
                "catid": 11042922,
                "parent_catid": 11042921,
                "name": "Rings",
                "display_name": "Rings",
                "image": "ea40479a9111557048bfd2b48bbab870",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042923,
                "parent_catid": 11042921,
                "name": "Earrings",
                "display_name": "Earrings",
                "image": "5b905808f2c70521db5b3e45a8d4814e",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042924,
                "parent_catid": 11042921,
                "name": "Scarves & Shawls",
                "display_name": "Scarves & Shawls",
                "image": "4594557c1cab8c8cb66982f995ae8e7f",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042925,
                "parent_catid": 11042921,
                "name": "Gloves",
                "display_name": "Gloves",
                "image": "c9cb9d46078a117602bfac788357dde5",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042930,
                "parent_catid": 11042921,
                "name": "Hair Accessories",
                "display_name": "Hair Accessories",
                "image": "022dc1a34af8d2032ed07cfbe029dc68",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042937,
                "parent_catid": 11042921,
                "name": "Bracelets & Bangles",
                "display_name": "Bracelets & Bangles",
                "image": "41497ea3e959cbf0fcc509ffbbf8e023",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042938,
                "parent_catid": 11042921,
                "name": "Anklets",
                "display_name": "Anklets",
                "image": "f3c5ff4fe051e233c018cba8aaf4c2ef",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042939,
                "parent_catid": 11042921,
                "name": "Hats & Caps",
                "display_name": "Hats & Caps",
                "image": "6d1d0ea7023fbc9bb345468412d81fc5",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042947,
                "parent_catid": 11042921,
                "name": "Necklaces",
                "display_name": "Necklaces",
                "image": "49a3eb003a887b424200b1e1e538b541",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042952,
                "parent_catid": 11042921,
                "name": "Eyewear",
                "display_name": "Eyewear",
                "image": "4d9c100065b790de5d7602ef092dbf83",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11053196,
                "parent_catid": 11042921,
                "name": "Contact Lens & Accessories",
                "display_name": "Contact Lens & Accessories",
                "image": "49b40b4692ea272ed201a675212dfae0",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042957,
                "parent_catid": 11042921,
                "name": "Investment Precious Metals",
                "display_name": "Investment Precious Metals",
                "image": "8b0641a8dfff227d3c65f9fcb32646b4",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042963,
                "parent_catid": 11042921,
                "name": "Belts",
                "display_name": "Belts",
                "image": "fd0fbbb1cc596bafad58b304b3eaa963",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042967,
                "parent_catid": 11042921,
                "name": "Neckties, Bow Ties & Cravats",
                "display_name": "Neckties, Bow Ties & Cravats",
                "image": "8016a6a77d4e89d06a5884697ae8ee6f",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042968,
                "parent_catid": 11042921,
                "name": "Additional Accessories",
                "display_name": "Additional Accessories",
                "image": "4cc525e27e8d19d524b240169b1115f1",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042976,
                "parent_catid": 11042921,
                "name": "Accessories Sets & Packages",
                "display_name": "Accessories Sets & Packages",
                "image": "6acb61fb74cd527656b0f8114934fb2f",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042978,
                "parent_catid": 11042921,
                "name": "Precious Metal Jewelries",
                "display_name": "Precious Metal Jewelries",
                "image": "85885baa708ceacb02c3d0e15f955585",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11042977,
                "parent_catid": 11042921,
                "name": "Other Fashion Accessories",
                "display_name": "Other Fashion Accessories",
                "image": "7c51fe3b37c392c22a7e424cc496d371",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            }
        ]
    },
    "error": 0,
    "error_msg": ""
}
let shopeeHomeLiving = {
    "data": {
        "category_list": [
            {
                "catid": 11043849,
                "parent_catid": 11043778,
                "name": "Home Improvement",
                "display_name": "Home Improvement",
                "image": "f4b153fdc4104b8ac253862792286ece",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043863,
                "parent_catid": 11043778,
                "name": "Tools",
                "display_name": "Tools",
                "image": "7ce50736206ae2e5b4224ea3a8f377e5",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043875,
                "parent_catid": 11043778,
                "name": "Home Care Tools",
                "display_name": "Home Care Tools",
                "image": "336dc2e285737527c5a1fe4b0ddb9df0",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043886,
                "parent_catid": 11043778,
                "name": "Home Care Supplies",
                "display_name": "Home Care Supplies",
                "image": "912d8ea485b867d2239ca6518d427538",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043895,
                "parent_catid": 11043778,
                "name": "Kitchen Utensils & Accessories",
                "display_name": "Kitchen Utensils & Accessories",
                "image": "9386e66094f08ca35008820150906529",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043909,
                "parent_catid": 11043778,
                "name": "Cookware",
                "display_name": "Cookware",
                "image": "d6393fb634245a035e7539a23540a542",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043922,
                "parent_catid": 11043778,
                "name": "Dinnerware",
                "display_name": "Dinnerware",
                "image": "a7b9c722ff3c1250d972930a9de8238d",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043934,
                "parent_catid": 11043778,
                "name": "Safety & Security",
                "display_name": "Safety & Security",
                "image": "c0b35734553d001bcf0a5aa230ba64b0",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043939,
                "parent_catid": 11043778,
                "name": "Home Organizers",
                "display_name": "Home Organizers",
                "image": "417013214e9739792c76a6191bb75781",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043950,
                "parent_catid": 11043778,
                "name": "Religious Supplies",
                "display_name": "Religious Supplies",
                "image": "9ca91f72f9df86818cf662cce6012167",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043952,
                "parent_catid": 11043778,
                "name": "Umbrella",
                "display_name": "Umbrella",
                "image": "7ac15e4339f2fe530b45def5701bc60c",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043779,
                "parent_catid": 11043778,
                "name": "Home Fragrance & Aromatherapy",
                "display_name": "Home Fragrance & Aromatherapy",
                "image": "ffce8e3d8f4fa4d114562dfbbc3876e8",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043783,
                "parent_catid": 11043778,
                "name": "Bathrooms",
                "display_name": "Bathrooms",
                "image": "a7642c806f374a39bfa5b6d2a58417e9",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043797,
                "parent_catid": 11043778,
                "name": "Bedding",
                "display_name": "Bedding",
                "image": "dd235c1eed65083f8b662e0dd5c830a6",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043807,
                "parent_catid": 11043778,
                "name": "Decoration",
                "display_name": "Decoration",
                "image": "0aacb8c870be959e824b9ee6bd9910f0",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043820,
                "parent_catid": 11043778,
                "name": "Furniture",
                "display_name": "Furniture",
                "image": "46eb4d29492212ed409199aa15c4d993",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043838,
                "parent_catid": 11043778,
                "name": "Gardening",
                "display_name": "Gardening",
                "image": "11173fe8adef4de047c46de5eafabf9a",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            },
            {
                "catid": 11043951,
                "parent_catid": 11043778,
                "name": "Other Home & Living",
                "display_name": "Other Home & Living",
                "image": "ced9259094b919b0f0263f8fe1826ac5",
                "unselected_image": null,
                "selected_image": null,
                "level": 2,
                "children": null,
                "block_buyer_platform": null
            }
        ]
    },
    "error": 0,
    "error_msg": ""
}